### ISSUE TITLE
Login to server

### ISSUE THREAD

**Issue by jelkner** [arltech2017/bikeshare-server#1]
I want to be able to point my browser at a URL and see a form with user and password fields and a submit button.  When I enter the user and password y'all give me (jelkner would be nice), and click the submit button, I want to see a message that says "Welcome jelkner, your bike is ready for you!"

**Comment by mjsir911** [comment]
Because of how we are doing things (oAuth through google), there will be a "Sign in through google" button which will ask you to sign in using google's sign in page.

**Comment by jelkner** [comment]
Nice.  Please consider my story to be modified thus:

I want to be able to point my browser at a URL and button which says "Sign in through Google".  Once authenticated in this way, I am taken to a page with a button that says "Check Out a Bike".  When I click that, I see a message that says "Your bike is ready for you!"

**Comment by mjsir911** [comment]
Working version [here](http://bikes.arlingtontech.us/)

**Comment by jelkner** [comment]
Nice work gentlemen!
